// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAE3QzN7bibymskQxsTrWH2vbiNoUnFCQ',
    appId: '1:695994828839:web:8395d5f633cc3724626602',
    messagingSenderId: '695994828839',
    projectId: 'jobsque-94ab8',
    authDomain: 'jobsque-94ab8.firebaseapp.com',
    storageBucket: 'jobsque-94ab8.appspot.com',
    measurementId: 'G-LJPFHD6NPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_FJLS_8dikf_m0uW8e5ItM3ORcfJVOk',
    appId: '1:695994828839:android:a87a45cdac11ae52626602',
    messagingSenderId: '695994828839',
    projectId: 'jobsque-94ab8',
    storageBucket: 'jobsque-94ab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkcsr3vXwKX7fRwA1ula4jeU2VCd1zes',
    appId: '1:695994828839:ios:085b27e1aa31c289626602',
    messagingSenderId: '695994828839',
    projectId: 'jobsque-94ab8',
    storageBucket: 'jobsque-94ab8.appspot.com',
    iosClientId: '695994828839-elhd20tfo7agpo5skvp3ulr3260c3lob.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgkcsr3vXwKX7fRwA1ula4jeU2VCd1zes',
    appId: '1:695994828839:ios:085b27e1aa31c289626602',
    messagingSenderId: '695994828839',
    projectId: 'jobsque-94ab8',
    storageBucket: 'jobsque-94ab8.appspot.com',
    iosClientId: '695994828839-elhd20tfo7agpo5skvp3ulr3260c3lob.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsque',
  );
}
